ALTER TABLE transactions
    ADD CommissionAmount float;
ALTER TABLE transactions
    ADD PurchaserCard varchar(16);
ALTER TABLE transactions
    ADD CardMonth integer;
ALTER TABLE transactions
    ADD CardYear integer;
ALTER TABLE transactions
    ADD PhoneNumber varchar(10);
ALTER TABLE transactions
    ADD TrackingCode varchar(255);
