swagger: "2.0"
info:
  title: "Qpay API"
  version: "1.0.0"

paths:
  /api/v1/register:
    post:
      summary: "Create a new user"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "User registration request"
          required: true
          schema:
            $ref: "#/definitions/RegisterRequest"
      responses:
        201:
          description: "User created successfully"
          schema:
            $ref: "#/definitions/RegisterResponse"
        400:
          description: "Bad Request"
        403:
          description: "validation error"
        409:
          description: "duplicate email, username, phone or identity"
        500:
          description: "Internal Server Error"

definitions:
  RegisterRequest:
    type: "object"
    properties:
      name:
        type: "string"
      username:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      phone_number:
        type: "string"
      identity:
        type: "string"
      address:
        type: "string"
      is_company:
        type: "boolean"
    required:
      - name
      - username
      - email
      - password
      - phone_number
      - identity
      - address
      - is_company

  RegisterResponse:
    type: "object"
    properties:
      status:
        type: "string"
      message:
        type: "string"
